### PR TITLE
Set execute permission on Unix shellscript

### PR DESCRIPTION
**Pull request by willend**
Execute permissions set

### CODE REVIEW

**Comment by mwittrock** [comment]
The execute bit is set in the repository, but since I'm doing the build on Windows at the moment, it's lost when the release ZIP is created, unfortunately.

**Comment by willend** [comment]
Roger. As suggested pr. mail also, an easy fix could be to roll the build through WSL.

**Comment by willend** [comment]
In fact it looks like there may be a more a windows-centric way https://medium.com/@akash1233/change-file-permissions-when-working-with-git-repos-on-windows-ea22e34d5cee

**Comment by mwittrock** [comment]
Will look into it, thanks.

**Pull request closed without merging**
